### PR TITLE
Fix transition for popped screen with custom transition

### PR DESCRIPTION
**Pull request by ilyasshafigin**
## Description

If using custom transition with `keyTransition`, then returning to previous screen occurred with wrong animation.

For example, there is screen A, B, C. Screens A and C open with a default transition. Screen B with a custom transition.
Open screens A -> B -> C. In this case all screens will display with a correct transition.
Now, if you go back to screen B, the transition from C to B will be with a custom animation, while it should be with a default transition, because screen C opened with default. 

For example, I added `DetailsCustomTransitionKey` with `VerticalSlideTransition`.

<details>
<summary>Screen record</summary>

https://user-images.githubusercontent.com/7170090/218724694-14022ed8-e6df-46b2-844e-ae95c4830850.mp4

</details>

## Solution

Fixed function `Navigator.getTransition`.
If there is a pop to previous screen, then take the transition for `previousEntry`.

<details>
<summary>Screen record</summary>

https://user-images.githubusercontent.com/7170090/218726074-c175c823-2114-4587-9530-6c0875faf203.mp4

</details>

### CODE REVIEW

**Comment by roudikk** [comment]
Thanks for the PR,

Yeah the logic here was incorrect, thanks for finding that out. 

Fix the conflicts and we can get this one in

**Comment by roudikk** [comment]
Thanks for the PR ! I actually was working on a fix at [b11a085](https://github.com/roudikk/guia/commit/b11a085c298befbe47484b3de53b02972382ded4). Basically, we should be running the logic in the when statement for the previous and new entry. To make sure both can have a fallback. Do you mind merging master to your branch and making sure that the custom key you added in the sample app still behaves as you expect?

**Comment by ilyasshafigin** [comment]
I merged your commit to my branch. Behavior is not as expected. Even the forward transition is not the same as before.
You have the transition associated with only one screen. I think the transition is defined between the current screen and the next screen, they have a similar animation. You have a combination of two different animations

<details>
  <summary>Screen record</summary>

https://user-images.githubusercontent.com/7170090/219593541-1fb6f858-539d-424f-8bd2-aeb5653c97b5.mp4

</details>

**Comment by roudikk** [comment]
> I merged your commit to my branch. Behavior is not as expected. Even the forward transition is not the same as before. You have the transition associated with only one screen. I think the transition is defined between the current screen and the next screen, they have a similar animation. You have a combination of two different animations
> 
> Screen record

I think your recording here is showing the proper transitions.

I gave this article a read:
https://medium.com/androiddevelopers/animations-in-navigation-compose-36d48870776b

image

So my understanding is the following:
- Details Screen plays its exit transition (Slide left + fade out) then custom key screen plays its enter (Slide in up)
- When you pop, the custom key will play its slide out while the details screen will play its slide in animation

That's basically what I understood when going through the fragment transition doc and the accompanist animation library for NavHost.

If I'm mistaken please let me know, it's actually quite confusing trying to understand.

**Comment by ilyasshafigin** [comment]
I'm confused too.
I think a navigation library has different approaches.
You want to use the same approach as the accompanist animation library, but there is a different API.
Let's say we use your approach. Can you please tell me how to achieve the same animation as here with `keyTransition`/`nodeTransition`?

<details>
<summary>Sample</summary>

https://user-images.githubusercontent.com/7170090/218726074-c175c823-2114-4587-9530-6c0875faf203.mp4

</details>

**Comment by roudikk** [comment]
That's actually a good point. I'm actually doing some research now and trying out different use cases to see what fits better in Guia.

**Comment by roudikk** [comment]
Alright, I think for Guia it makes more sense the previous/your approach. Let's go with your changes! Fix conflicts and let's get this PR in. Thank you!

**Review by roudikk — APPROVED** [review]

**Pull request merged**
